# Change these first
owner: uzumaki258 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: DataTrungWeb
    url: $DATATRUNGWEB
    assignees:
      - uzumaki258
  - name: MainDataLSWeb
    url: $MAINDATALSWEB
    assignees:
      - uzumaki258
  - name: IMG SERVICE
    url: $IMG_SERVICE
    assignees:
      - uzumaki258
  - name: Mobile Search LS
    url: $MOBILESEARCHLS
    assignees:
      - uzumaki258
    method: GET
    headers:
    - "Authorization: Bearer $LS_TOKEN"
    expect:
      statusCode: 200
      body:
        success: true
        data:
          items:
            - name: "$SEARCH_TERM"
  - name: Vultr Object
    url: $VULTR_OBJECT
    assignees:
      - uzumaki258
  - name: Third Party
    url: $THIRD_PARTY_URL
    assignees:
      - uzumaki258
    headers:
      - "User-Agent: $UA_STRING"
  - name: Third Party IMG
    url: $THIRD_PARTY_IMG
    assignees:
      - uzumaki258

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.appixi.net
  theme: night
  #baseUrl: status.appixi.net
  logoUrl: https://appixi.net/assets/img/logo/logo_single.svg
  favicon: https://appixi.net/assets/img/favicon.ico
  name: Appixi Status
  introTitle: "Welcome to Appixi Status Page"
  introMessage: This is a Appixi status page which uses **real-time** data from our [GitHub repository](https://github.com/uzumaki258/status). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Operation Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
