# Change these first
owner: uzumaki258 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: DataTrungWeb
    url: $DATATRUNGWEB
    assignees:
      - uzumaki258
  - name: MainDataLSWeb
    url: $MAINDATALSWEB
    assignees:
      - uzumaki258
  - name: IMG SERVICE
    url: $IMG_SERVICE
    assignees:
      - uzumaki258
  - name: Mobile Search LS
    url: $MOBILESEARCHLS
    assignees:
      - uzumaki258
    method: GET
    headers:
    - "Authorization: Bearer $LS_TOKEN"
    expect:
      statusCode: 200
      body:
        success: true
        data:
          items:
            - name: "$SEARCH_TERM"
  - name: Detail Mobile LS
    url: $DETAIL_MOBILE_URL
    assignees:
      - uzumaki258
    method: GET
    headers:
    - "Authorization: Bearer $LS_TOKEN"
    expect:
      statusCode: 200
      body:
        success: true
        data:
          items:
            - name: "$DETAIL_SEARCH_TERM"
  - name: Mobile Top Click
    url: $MOBILE_TOP_CLICK
    assignees:
      - uzumaki258
    method: GET
    headers:
    - "Authorization: Bearer $LS_TOKEN"
    expect:
      statusCode: 200
      body:
        success: true
  - name: Mobile Search Tag
    url: $MOBILE_SEACH_TAG
    assignees:
      - uzumaki258
    method: GET
    headers:
    - "Authorization: Bearer $LS_TOKEN"
    expect:
      statusCode: 200
      body:
        success: true
  - name: Vultr Object
    url: $VULTR_OBJECT
    assignees:
      - uzumaki258
  - name: Third Party
    url: $THIRD_PARTY_URL
    assignees:
      - uzumaki258
    headers:
      - "User-Agent: $UA_STRING"
  - name: Third Party IMG
    url: $THIRD_PARTY_IMG
    assignees:
      - uzumaki258
  - name: Backup Uq
    url: $BACKUP_URL
    assignees:
      - uzumaki258
    method: GET
    headers:
      - "Api-Key: $KEY_UQ"
    expect:
      statusCode: 200
      body:
        active: true
        remaining:
          total: null
  - name: Backup Rb
    url: $BACKUP_URL
    assignees:
      - uzumaki258
    method: GET
    headers:
      - "Api-Key: $KEY_RB"
    expect:
      statusCode: 200
      body:
        active: true
        remaining:
          total: null
  - name: Backup Kg
    url: $BACKUP_URL
    assignees:
      - uzumaki258
    method: GET
    headers:
      - "Api-Key: $KEY_KG"
    expect:
      statusCode: 200
      body:
        active: true
        remaining:
          total: null
  - name: Backup Cu
    url: $BACKUP_URL
    assignees:
      - uzumaki258
    method: GET
    headers:
      - "Api-Key: $KEY_CU"
    expect:
      statusCode: 200
      body:
        active: true
        remaining:
          total: null

  - name: EMTK
    url: $EM_API
    method: GET
    statusCode: 200
    customScript: |
      echo "Starting custom script..."
      response=$(curl --silent --location '${{ secrets.EM_API }}')
      echo "Response: $response"
      token=$(echo $response | jq -r '.data.em_token')
      echo "Token: $token"
      if [ -z "$token" ]; then
        echo "Failed to retrieve token."
        exit 1
      fi
      payload=$(echo $token | cut -d '.' -f 2 | base64 --decode --ignore-garbage)
      echo "Payload: $payload"
      exp=$(echo $payload | jq -r '.exp')
      echo "Expiration time: $exp"
      current_time=$(date +%s)
      echo "Current time: $current_time"
      if [ true ]; then  # Force the condition to always be true
        echo "The token is expired."
        exit 1
      else
        echo "The token is valid."
        exit 0
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.appixi.net
  theme: night
  #baseUrl: status.appixi.net
  logoUrl: https://appixi.net/assets/img/logo/logo_single.svg
  favicon: https://appixi.net/assets/img/favicon.ico
  name: Appixi Status
  introTitle: "Welcome to Appixi Status Page"
  introMessage: This is a Appixi status page which uses **real-time** data from our [GitHub repository](https://github.com/uzumaki258/status). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Operation Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
